# Generated by Django 4.0.2 on 2022-02-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_backend', '0002_rename_user_comment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='reply_id',
            new_name='reply',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='reply_id',
            new_name='reply',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='user_id',
            new_name='user',
        ),
    ]
